name: 2025全自动生产流水线

on:
  schedule:
    - cron: '0 2 * * *'  # 每天北京时间10AM触发
  workflow_dispatch:     # 支持手动触发

jobs:
  generate-products:
    runs-on: windows-2025-ai
    steps:
    - name: 量子克隆仓库
      uses: actions/checkout@v4
      with:
        lfs: true
        quantum-tunnel: true
        
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: 安装AI生成组件
      run: |
        pip install midjourney-api==2025.3.1
        pip install blender-client==4.2.5
        
    - name: 执行每日生成任务
      run: python src/auto_generate.py --mode full
        
    - name: 上传到电商平台
      run: python src/auto_upload.py --platform amazon,etsy